### ISSUE TITLE
Also use `mclapply` as backend?

### ISSUE THREAD

**Issue by albert-ying** [moosa-r/parapurrr#1]
Hi Moosa -- Thank you for creating this! I was also considering creating something like this and now I don't have to!

I was a user of `furrr`. It is great, but it is not efficient on RAM (likely because of the `future`). A similar RAM problem doesn't show up when I use `mcapply` -- that's the original reason I want to switch.

You may know more about this than me, I'm wondering how `foreach` compares to `mclapply`, and  is `doParalelle` the same thing as `mclapply`?

Thank you!

**Comment by albert-ying** [comment]
Also, will the progress bar be added at some point?

**Comment by moosa-r** [comment]
Dear Albert

Glad you have found this useful. This package is really in its infancy. I hope to - someday - come up with time or some kind of motivation to further develop and promote it. :) 

As far as I understand, when using the doParallel backend and forking in Unix, and doMC (that only supports forking), the foreach's %dopar% will internally use mclapply (please see: https://github.com/cran/doParallel/blob/master/R/doParallel.R ). To ensure that, [I made a minor change](https://github.com/moosa-r/parapurrr/commit/7a48d746e105c8751fd3813e1190ecca4e7978df) in how the parapurrr package registers the doParallel backend. Hence mclapply is - albeit indirectly- supported by parapurrr.

Regarding the progress bar, I haven't found a consistent way to implement it with different backends. It is supported in doSNOW and Future. Thus, implementing it only requires adding an argument to the exported function and minor tweaking in the internal function. However, given that not all backends support the progress bar, the codes and results will not be clean, so I prefer to drop it in the meantime. Unfortunately, this means that currently the closest thing we can have to the progress bar is setting the .verbose argument to TRUE. 
As soon as I come up with a time, I will do my best to find a universal and clean way to implement the progress bar, If possible of course. I will appreciate any help or contribution in this regard.

Cheers

**Comment by moosa-r** [comment]
P.s: the workflow fails due to dependency problems. doMC is not available in Windows and Rmpi on Unix-based OS. Otherwise, the package works just fine. :)

**Comment by albert-ying** [comment]
Thank you so much for the clarification!
